# Generated by Django 3.2.8 on 2021-10-22 02:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=3, editable=False, populate_from='user'),
            preserve_default=False,
        ),
    ]
